#version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_pass
      POSTGRES_DB: ems_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: ems_user
      DB_PASSWORD: ems_pass
      DB_NAME: ems_db
      DB_PORT: "5432"
      ALLOWED_ORIGINS: "*"
    ports:
      - "8080:8080"


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER_URL=http://3.140.247.240:8080/employees

volumes:
  pgdata: